apiVersion: v2
type: application

# Information about clowder.
name: clowder
icon: https://isda.ncsa.illinois.edu/~kooper/charts/images/clowder.png
home: https://clowderframework.org/
description: >
  Open Source Data Management for Long Tail Data. Clowder is a customizable and
  scalable data management framework to support any data format and multiple
  research domains.

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.10.1

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
appVersion: 1.15.1

# List of people that maintain this helm chart.
maintainers:
  - name: Rob Kooper
    email: kooper@illinois.edu

# location of source code
sources:
  - https://github.com/clowder-framework/clowder

# Dependencies for clowder. Some of the dependencies are only installed if they
# are enabled.
dependencies:
  - name: mongodb
    version: ~7.2
    repository: https://charts.bitnami.com/bitnami
    condition: mongodb.enabled
  - name: minio
    version: ~3.4
    repository: https://charts.bitnami.com/bitnami
    condition: minio.enabled
  - name: rabbitmq
    version: ~7.6
    repository: https://charts.bitnami.com/bitnami
    condition: rabbitmq.enabled
  - name: elasticsearch2
    alias: elasticsearch
    version: ~0.2
    repository: https://opensource.ncsa.illinois.edu/charts/
    condition: elasticsearch.enabled

annotations:
  artifacthub.io/links: |
    - name: Helm Chart
      url: https://github.com/clowder-framework/clowder-helm
  artifacthub.io/changes: |
    - Update clowder to 0.15.1
      - Several views were throwing errors trying to access a None value in EventSinkService when a user was not logged in.
      - Changed EventSinkService logging to debug to minimize chatter.
      - Don't automatically create eventsink queue and bind it to eventsink exchange. Let clients do that so that we don't have a queue for the eventsink filling up if there are no consumers.
    - Update digest extractor to 2.2.0
