name: Release Charts

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get dependencies
        run: helm dep build

      - name: Publish to NCSA OpenSource
        uses: bsord/helm-push@v3
        with:
          username: ${{ secrets.HELM_USERNAME }}
          password: ${{ secrets.HELM_PASSWORD }}
          repository-url: "https://opensource.ncsa.illinois.edu/charts"
          chart-folder: "."
          force: false
